dbt:
  target: dev
  outputs:
    dev:
      type: sqlite
      schema: "main"
      threads: 1
      database: "database"
      schemas_and_paths:
        main: "C:/Users/james/Jupyter/syncopation-study/make-sqlite/dbt/data.sqlite3"
      schema_directory: "C:/Users/james/Jupyter/syncopation-study/make-sqlite/dbt/"