dbt:
  outputs:
    prod:
      type: sqlite
      threads: 1
      database: "C:\Users\james\Jupyter\syncopation-study\make-sqlite\dbt\data.sqlite3"
      schema: 'main'
      schemas_and_paths:
        main: "C:\Users\james\Jupyter\syncopation-study\make-sqlite\dbt\data.sqlite3"
      schema_directory: "models"
  target: prod