version: 2

models:
  - name: midi_files
    description: |
      A model describing MIDI files. MIDI files can be linked to
      multiple spotify tracks from one or more artists. See
      derived views (e.g., spotify_tracks_flat) for more useful
      analytic tables.
    columns:
      - name: md5
        tests:
          - not_null
          - unique
      - name: instruments
        description: |
          Number of instruments in the MIDI file.
        tests:
          - not_null
      - name: summed_WNBD
        description: summed WNBD score across all bars.
      - name: mean_WNBD_per_bar
        description: mean WNBD score.
      - name: number_of_bars
      - name: number_of_bars_not_measured
      - name: bars_with_valid_output
      - name: bars_without_valid_output
  - name: spotify_tracks
    description: |
      Contains information about a Spotify track that was linked to one of the MIDI files.
    columns:
      - name: spotify_id
        description: Unique identifier from Spotify API.
        tests:
          - unique
          - not_null
      - name: title
        description: The name of the song.
        tests:
          - not_null
      - name: album_id
        description: The Spotify id of the album that the song is in
        tests:
          - not_null
      - name: artist_ids
        description: Spotify ids of the artists on the song. Comma separated if multiple.
        tests:
          - not_null
      - name: year_first_released
        tests:
          - not_null
      - name: duration_ms
        description: duration of the song in milliseconds.
        tests:
          - not_null
      - name: popularity
        description: |
          From Spotify API, The popularity of the track.
          The value will be between 0 and 100, with 100 being the most popular.
      - name: has_features
        description: Whether or not the track has an associated entry in audio_features.
        tests:
          - not_null
  - name: audio_features
    description: Information about the audio analysis of certain Spotify songs extracted from the API before the audio-features endpoint was deprecated.
    columns:
      - name: spotify_id
        description: Unique identifier from Spotify API.
        tests:
          - unique
          - not_null
          relationships:
            to: ref("spotify_tracks")
            field: spotify_id
      - name: danceability
        description: |
          From Spotify API, Danceability describes how suitable a track is for dancing based on a combination of musical elements
          including tempo, rhythm stability, beat strength, and overall regularity. A value of 0.0 is least danceable and 1.0 is most danceable.
        tests:
          - non_null
      - name: acousticness
        description: |
          From Spotify API, A confidence measure from 0.0 to 1.0 of whether the track is acoustic. 
          1.0 represents high confidence the track is acoustic.
        tests:
          - non_null
      - name: energy
        description: |
          Energy is a measure from 0.0 to 1.0 and represents a perceptual measure of intensity and activity. Typically, energetic tracks feel fast, loud, and noisy. For example, death metal has high energy, while a Bach prelude scores low on the scale. 
          Perceptual features contributing to this attribute include dynamic range, perceived loudness, timbre, onset rate, and general entropy.
        tests:
          - non_null
      - name: valence
        description: |
          A measure from 0.0 to 1.0 describing the musical positiveness conveyed by a track. Tracks with high valence sound more positive
          (e.g. happy, cheerful, euphoric), while tracks with low valence sound more negative (e.g. sad, depressed, angry).
        tests:
          - non_null
      - name: speechiness
        description: |
          Speechiness detects the presence of spoken words in a track.
          The more exclusively speech-like the recording (e.g. talk show, audio book, poetry), the closer to 1.0 the attribute value. 
          Values above 0.66 describe tracks that are probably made entirely of spoken words. Values between 0.33 and 0.66 describe tracks that may contain both music and speech, either in sections or layered, 
          including such cases as rap music. Values below 0.33 most likely represent music and other non-speech-like tracks.
        tests:
          - non_null
      - name: instrumentalness
        description: |
          Predicts whether a track contains no vocals. 
          "Ooh" and "aah" sounds are treated as instrumental in this context. 
          Rap or spoken word tracks are clearly "vocal". The closer the instrumentalness value is to 1.0, the greater likelihood 
          the track contains no vocal content. Values above 0.5 are intended to represent instrumental tracks, but confidence is 
          higher as the value approaches 1.0.
        tests:
          - non_null
  - name: artists
    columns:
      - name: artist_id
        tests:
          - non_null
      - name: title
        tests:
          - non_null
  - name: albums
    columns:
      - name: album_id
        tests:
          - non_null
      - name: title
        tests:
          - non_null
  - name: midi_spotify_map
    description: |
      A junction table representing the many-to-many relationship between MIDI files and Spotify Tracks.
    columns:
      - name: md5
        tests:
          - relationships:
              to: ref("midi_files")
              field: md5
      - name: spotify_id
        tests:
          - relationships:
              to: ref("spotify_tracks")
              field: spotify_id
      - name: score
        description: A 0 to 1 value representing the confidence of the link.
        tests:
          - not_null
  - name: best_midi_to_spotify_flat
    description: |
      A flat model of MIDI-Spotify link data. Each MIDI file is joined with
      the highest-confidence Spotify track it is linked with.
    columns:
      - name: md5
        tests:
          - unique
          - relationships:
              to: ref("midi_files")
              field: md5
  - name: best_spotify_to_midi_flat
    description: |
      A flat model of Spotify_MIDI link data. Each Spotify track is joined with
      the highest-confidence MIDI file it is linked with.
    columns:
      - name: spotify_id
        tests:
          - unique
          - relationships:
              to: ref("spotify_tracks")
              field: spotify_id
  - name: best_midi_to_spotify_flat_with_features
    description: |
      A view of best_midi_to_spotify_flat with only spotify tracks that have features,
      with those features included.
    columns: